Repository niolabs/nio, pull requests merged in 2018-06, with the labels that each got.

#132 NIO 1134: Timestamp format normalizing
  nio/util/logging/handlers/publisher/handler.py
  nio/util/logging/handlers/publisher/tests/test_handler.py
Labels: change/fixed

#134 NIO-1106, returning service+block statuses, fixes to runner to avoid …
  nio/block/base.py
  nio/block/context.py
  nio/block/tests/test_block_base.py
  nio/router/base.py
  nio/router/tests/test_notify_management_signals.py
  nio/service/base.py
  nio/service/tests/test_service_base.py
  nio/testing/block_test_case.py
  nio/testing/tests/test_block_test_case.py
  nio/util/flags_enum.py
  nio/util/runner.py
  nio/util/tests/test_flags_enum.py
Labels: change/changed

#135 Add set_status method in block base
  nio/block/base.py
  nio/block/tests/test_block_base.py
Labels: change/added
